package xposts

// nolint
// autogenerated code using github.com/haasted/alias-generator.
// based on functionality in github.com/rigelrozanski/multitool

import (
	"github.com/desmos-labs/desmos/x/ibc/xposts/internal/keeper"
	"github.com/desmos-labs/desmos/x/ibc/xposts/internal/types"
)

const (
	ModuleName   = types.ModuleName
	Version      = types.Version
	PortID       = types.PortID
	StoreKey     = types.StoreKey
	RouterKey    = types.RouterKey
	PortKey      = types.PortKey
	QuerierRoute = types.QuerierRoute
)

var (
	// functions aliases
	NewKeeper      = keeper.NewKeeper
	DefaultGenesis = types.DefaultGenesis
	RegisterCodec  = types.RegisterCodec

	// variable aliases
	ModuleCdc = types.ModuleCdc
)

type (
	Keeper          = keeper.Keeper
	GenesisState    = types.GenesisState
	AckDataCreation = types.AckDataCreation
)
