package posts

// nolint
// autogenerated code using github.com/haasted/alias-generator.
// based on functionality in github.com/rigelrozanski/multitool

import (
	"github.com/desmos-labs/desmos/x/ibc/posts/internal/keeper"
	"github.com/desmos-labs/desmos/x/ibc/posts/internal/types"
)

const (
	DefaultPacketTimeout          = keeper.DefaultPacketTimeout
	DefaultPacketTimeoutTimestamp = keeper.DefaultPacketTimeoutTimestamp
	EventTypeTimeout              = types.EventTypeTimeout
	EventTypePacket               = types.EventTypePacket
	EventTypeChannelClose         = types.EventTypeChannelClose
	AttributeKeyCreator           = types.AttributeKeyCreator
	AttributeKeyPostID            = types.AttributeKeyPostID
	AttributeKeyAckSuccess        = types.AttributeKeyAckSuccess
	AttributeKeyAckError          = types.AttributeKeyAckError
	ModuleName                    = types.ModuleName
	Version                       = types.Version
	PortID                        = types.PortID
	StoreKey                      = types.StoreKey
	RouterKey                     = types.RouterKey
	PortKey                       = types.PortKey
	QuerierRoute                  = types.QuerierRoute
)

var (
	// functions aliases
	NewKeeper                 = keeper.NewKeeper
	NewMsgCrossPost           = types.NewMsgCrossPost
	NewPostCreationPacketData = types.NewPostCreationPacketData
	RegisterCodec             = types.RegisterCodec
	DefaultGenesis            = types.DefaultGenesis

	// variable aliases
	ModuleCdc              = types.ModuleCdc
	AttributeValueCategory = types.AttributeValueCategory
)

type (
	Keeper                            = keeper.Keeper
	MsgCrossPost                      = types.MsgCrossPost
	PostCreationPacketData            = types.PostCreationPacketData
	PostCreationPacketAcknowledgement = types.PostCreationPacketAcknowledgement
	AckDataCreation                   = types.AckDataCreation
	ChannelKeeper                     = types.ChannelKeeper
	PortKeeper                        = types.PortKeeper
	GenesisState                      = types.GenesisState
)
