package magpie

// nolint
// autogenerated code using github.com/haasted/alias-generator.
// based on functionality in github.com/rigelrozanski/multitool

import (
	"github.com/desmos-labs/desmos/x/magpie/internal/keeper"
	"github.com/desmos-labs/desmos/x/magpie/internal/simulation"
	"github.com/desmos-labs/desmos/x/magpie/internal/types"
)

const (
	OpWeightMsgCreatePost     = simulation.OpWeightMsgCreatePost
	EventTypeCreateSession    = types.EventTypeCreateSession
	AttributeKeySessionID     = types.AttributeKeySessionID
	AttributeKeyNamespace     = types.AttributeKeyNamespace
	AttributeKeyExternalOwner = types.AttributeKeyExternalOwner
	AttributeKeyExpiry        = types.AttributeKeyExpiry
	AttributeValueCategory    = types.AttributeValueCategory
	ModuleName                = types.ModuleName
	RouterKey                 = types.RouterKey
	StoreKey                  = types.StoreKey
	ActionCreationSession     = types.ActionCreationSession
)

var (
	// functions aliases
	DecodeStore              = simulation.DecodeStore
	RandomizedGenState       = simulation.RandomizedGenState
	WeightedOperations       = simulation.WeightedOperations
	SimulateMsgCreateSession = simulation.SimulateMsgCreateSession
	RandomSessionData        = simulation.RandomSessionData
	ParseSessionID           = types.ParseSessionID
	NewSession               = types.NewSession
	RegisterCodec            = types.RegisterCodec
	NewGenesisState          = types.NewGenesisState
	DefaultGenesisState      = types.DefaultGenesisState
	ValidateGenesis          = types.ValidateGenesis
	SessionStoreKey          = types.SessionStoreKey
	NewMsgCreateSession      = types.NewMsgCreateSession
	NewKeeper                = keeper.NewKeeper
	NewQuerier               = keeper.NewQuerier
	NewHandler               = keeper.NewHandler

	// variable aliases
	ModuleCdc             = types.ModuleCdc
	SessionLengthKey      = types.SessionLengthKey
	LastSessionIDStoreKey = types.LastSessionIDStoreKey
	SessionStorePrefix    = types.SessionStorePrefix
	RandomNamespaces      = simulation.RandomNamespaces
)

type (
	Keeper       = keeper.Keeper
	SessionData  = simulation.SessionData
	SessionID    = types.SessionID
	Session      = types.Session
	Sessions     = types.Sessions
	GenesisState = types.GenesisState
)
